version: '2'
services:
    nginx:
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        restart: unless-stopped
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        restart: unless-stopped
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
    pma:
        restart: unless-stopped
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 8183:80
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret